[[constraint]]
  name = "github.com/shopspring/decimal"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"
